variable "org_id" {}
variable "orchestration_project_number" {}
variable "orchestration_project_id" {}
variable "analytics_project" {}
variable "region" {}
variable "billing_account" {}
variable "owner" {}
variable "owner_email" {}
variable "kubeflow_host" {}
variable "inception_ip" {}
